name: Code action test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Force failure
        run: |
          echo "::error::This is a forced error message"
          exit 1

      - name: Setup Code tunnel
        if: ${{ failure() }}
        uses: ./
        continue-on-error: true
